english_text_map = {
    'answer_no': 'No',
    'answer_region_no': "I haven't been in any of the mentioned regions",
    'answer_unknown': "I don't know",
    'answer_yes': 'Yes',
    'app_root_all_rights_reserved': 'All rights reserved',
    'app_root_data_privacy_link': 'Privacy Policy',
    'app_root_faq_link': 'FAQ',
    'app_root_imprint_link': 'Imprint',
    'app_root_legal_link': 'Legal',
    'button_continue': 'Continue to questions',
    'button_delete_qr_code': 'Complete the questionnaire',
    'button_show_code': 'Show created QR code',
    'button_start_now': 'Start questionnaire',
    'cookie_bar_accept': 'Accept',
    'cookie_bar_data_privacy': 'data protection declaration',
    'cookie_bar_reject': 'decline',
    'cookie_bar_text': 'With your consent, D4L data4life analyzes your use of the CovApp in order to improve the CovApp for all users. If you would like to consent to the transmission of analysis data, please click on "Accept". You can also use the CovApp without consent to the analysis of your use of the CovApp. Further information can be found in the ',
    'cookie_bar_text_dnt': 'We use cookies for a better user experience. Your "Do not track" browser setting will be taken into account and no analysis will take place. ',
    'data_privacy_content': '',
    'data_privacy_headline': 'data protection declaration',
    'disclaimer_headline': 'Note',
    'disclaimer_paragraph_1': 'Using this app does not replace medical treatment and does not provide any diagnostic services. The CovApp is used to improve the procedures in the Charité examination center and other outpatient clinics in connection with the new SARS-CoV-2 coronavirus. \ nIf you are currently feeling seriously ill, please see a doctor or medical help immediately. ',
    'disclaimer_paragraph_2': 'This website uses a cookie, which is required to operate the website. Personal data that allow conclusions to be drawn about your person will not be saved. ',
    'disclaimer_sub_headline_1': 'Notice on the use of cookies',

'faq_content': 'About the Coronavirus \ nThe scientific name of the novel coronavirus is "SARS-CoV-2". This virus can cause respiratory disease. This disease is called "COVID-19". Because the infectious disease COVID-19 has already spread across countries and continents, one speaks of a pandemic. \ N \ nThe transmission \ nThe novel coronavirus is transmitted via the so-called droplet infection. This can happen directly from person to person if droplets containing viruses enter the respiratory tract through the mouth or nose or the conjunctiva. But indirect infection is also possible if droplets come into contact with the mucous membranes via the hands. Signs of illness appear on average after 5 to 6, maximum 14 days after being infected. \ N \ nThe signs of illness \ nIf there is an infection with the coronavirus, it is easy for most people and is not life-threatening. This also applies to pregnant women and children. Mild symptoms can be flu-like symptoms such as dry cough, fatigue and fever. In addition, some patients suffer from sore throats, headache and body aches, and chills. It is currently assumed that 4 out of 5 infections are mild. In some people, however, the virus can lead to a more severe course with breathing problems up to bilateral pneumonia. These are often older people and patients with pre-existing conditions such as cardiovascular diseases, chronic respiratory diseases, diabetes, high blood pressure or cancer. These severe cases must be treated in intensive care in the hospital. If you feel sick, take the coronavirus test. \ N \ nSolidarity \ nAlthough Germany has a very good health system, it is not set for a steep increase, especially for the patients requiring intensive medical care. However, if it is possible to delay the increase in serious illnesses over a longer period of time, infected people will continue to be well cared for. Therefore, the main focus is currently on slowing down the infection rate. This can only succeed if all citizens go a distance. For protection, especially of the older generation and chronically ill people, everyone should take the situation seriously and limit social contacts as much as possible. However, please provide elderly, elderly or chronically ill relatives or neighbors and single people in need of help with food and everyday necessities. Keep an open ear for your concerns and communicate with each other - but please keep a distance of 2 meters. Act in solidarity. \ N \ nProtection \ nTo slow down the spread of the corona virus, you should avoid touching it when greeting, for example, and wash your hands regularly and thoroughly for at least 20 seconds with soap and water. Keep your distance when coughing or sneezing - just turn away from your opponent. Sneeze into the crook of your arm or into a tissue, which you should always dispose of afterwards. Avoid touching your mouth, eyes or nose with your hands. Share objects that you touch with your mouth, such as Cups or bottles, not with other people. Stay at home. \ N \ nTherapy \ nTreatment of the infection depends on the severity of the clinical picture. Mild cases do not have to be treated and can be cured at home. Severe pneumonia is e.g. treated by the administration of oxygen, the balance of fluids or antibiotics for the treatment of accompanying bacterial infections. This usually happens in the hospital. \ N \ nVaccination \ nThe vaccine is being developed. However, there is currently no vaccine available to protect against the novel coronavirus. \ N \ nStay informed! \ NThe Federal Ministry of Health regularly updates the information on the coronavirus: \ nhttps: //www.bundesgesundheitsministerium.de/coronavirus.html \ n \ nThe Charité scientist Prof. Dr. Christian Drosten keeps her up to date in the NDR podcast: \ nhttps ": //www.ndr.de/nachrichten/info/Corona-Podcast-Alle-Folgen-in-der-Uebersicht,podcastcoronavirus134.html ',
    'faq_headline': 'FAQ Coronavirus',
    'found_code': 'A QR code was found',
    'imprint_content': '',
    'imprint_headline': '',
    'input_date_error': 'Invalid date. Please try again.',
    'input_date_error_future': 'The date may not be in the future.',
    'input_date_help': 'Please enter a valid date in form DD.MM.YYYYY which is not in the future. Example: 09.03.2020',
    'input_date_label': 'please enter the date.',
    'input_date_placeholder': 'DD.MM.YYYY',
    'legal_first_paragraph': '',
    'legal_headline': 'Legal matters',
    'q01_option0': 'Younger than 40',
    'q01_option1': '40-50',
    'q01_option2': '51-60',
    'q01_option3': '61-70',
    'q01_option4': '71-80',
    'q01_option5': 'Older than 80',
    'q01_text': 'How old are you?',
    'q02_option0': 'living alone',
    'q02_option1': 'together with family, flat mates or assisted living',
    'q02_text': 'Wie ist Ihre aktuelle Wohnsituation?',
    'q03_option0': 'Housing situation',
    'q03_option1': 'In a community facility (school, day care center, university, home etc.)',
    'q03_option2': 'No, in none of the limited areas',
    'q03_text': 'Are you working in any of the following areas?',
    'q04_text': 'Do you smoke??',
    'q05_text': 'Have you traveled within last 4 weeks?',
}
