english_text_map = {
    'answer_no': 'No',
    'answer_region_no': "I haven't been in any of the mentioned regions",
    'answer_unknown': "I don't know",
    'answer_yes': 'Yes',
    'app_root_all_rights_reserved': 'All rights reserved',
    'app_root_data_privacy_link': 'Privacy Policy',
    'app_root_faq_link': 'FAQ',
    'app_root_imprint_link': 'Imprint',
    'app_root_legal_link': 'Legal',
    'button_continue': 'Continue to questions',
    'button_delete_qr_code': 'Complete the questionnaire',
    'button_show_code': 'Show created QR code',
    'button_start_now': 'Start questionnaire',
    'cookie_bar_accept': 'Accept',
    'cookie_bar_data_privacy': 'data protection declaration',
    'cookie_bar_reject': 'decline',
    'cookie_bar_text': 'With your consent, D4L data4life analyzes your use of the CovApp in order to improve the CovApp for all users. If you would like to consent to the transmission of analysis data, please click on "Accept". You can also use the CovApp without consent to the analysis of your use of the CovApp. Further information can be found in the ',
    'cookie_bar_text_dnt': 'We use cookies for a better user experience. Your "Do not track" browser setting will be taken into account and no analysis will take place. ',
    'data_privacy_content': '',
    'data_privacy_headline': 'data protection declaration',
    'disclaimer_headline': 'Note',
    'disclaimer_paragraph_1': 'Using this app does not replace medical treatment and does not provide any diagnostic services. The CovApp is used to improve the procedures in the Charité examination center and other outpatient clinics in connection with the new SARS-CoV-2 coronavirus. \ nIf you are currently feeling seriously ill, please see a doctor or medical help immediately. ',
    'disclaimer_paragraph_2': 'This website uses a cookie, which is required to operate the website. Personal data that allow conclusions to be drawn about your person will not be saved. ',
    'disclaimer_sub_headline_1': 'Notice on the use of cookies',
    'faq_content': 'About the Coronavirus \ nThe scientific name of the novel coronavirus is "SARS-CoV-2". This virus can cause respiratory disease. This disease is called "COVID-19". Because the infectious disease COVID-19 has already spread across countries and continents, one speaks of a pandemic. \ N \ nThe transmission \ nThe novel coronavirus is transmitted via the so-called droplet infection. This can happen directly from person to person if droplets containing viruses enter the respiratory tract through the mouth or nose or the conjunctiva. But indirect infection is also possible if droplets come into contact with the mucous membranes via the hands. Signs of illness appear on average after 5 to 6, maximum 14 days after being infected. \ N \ nThe signs of illness \ nIf there is an infection with the coronavirus, it is easy for most people and is not life-threatening. This also applies to pregnant women and children. Mild symptoms can be flu-like symptoms such as dry cough, fatigue and fever. In addition, some patients suffer from sore throats, headache and body aches, and chills. It is currently assumed that 4 out of 5 infections are mild. In some people, however, the virus can lead to a more severe course with breathing problems up to bilateral pneumonia. These are often older people and patients with pre-existing conditions such as cardiovascular diseases, chronic respiratory diseases, diabetes, high blood pressure or cancer. These severe cases must be treated in intensive care in the hospital. If you feel sick, take the coronavirus test. \ N \ nSolidarity \ nAlthough Germany has a very good health system, it is not set for a steep increase, especially for the patients requiring intensive medical care. However, if it is possible to delay the increase in serious illnesses over a longer period of time, infected people will continue to be well cared for. Therefore, the main focus is currently on slowing down the infection rate. This can only succeed if all citizens go a distance. For protection, especially of the older generation and chronically ill people, everyone should take the situation seriously and limit social contacts as much as possible. However, please provide elderly, elderly or chronically ill relatives or neighbors and single people in need of help with food and everyday necessities. Keep an open ear for your concerns and communicate with each other - but please keep a distance of 2 meters. Act in solidarity. \ N \ nProtection \ nTo slow down the spread of the corona virus, you should avoid touching it when greeting, for example, and wash your hands regularly and thoroughly for at least 20 seconds with soap and water. Keep your distance when coughing or sneezing - just turn away from your opponent. Sneeze into the crook of your arm or into a tissue, which you should always dispose of afterwards. Avoid touching your mouth, eyes or nose with your hands. Share objects that you touch with your mouth, such as Cups or bottles, not with other people. Stay at home. \ N \ nTherapy \ nTreatment of the infection depends on the severity of the clinical picture. Mild cases do not have to be treated and can be cured at home. Severe pneumonia is e.g. treated by the administration of oxygen, the balance of fluids or antibiotics for the treatment of accompanying bacterial infections. This usually happens in the hospital. \ N \ nVaccination \ nThe vaccine is being developed. However, there is currently no vaccine available to protect against the novel coronavirus. \ N \ nStay informed! \ NThe Federal Ministry of Health regularly updates the information on the coronavirus: \ nhttps: //www.bundesgesundheitsministerium.de/coronavirus.html \ n \ nThe Charité scientist Prof. Dr. Christian Drosten keeps her up to date in the NDR podcast: \ nhttps ": //www.ndr.de/nachrichten/info/Corona-Podcast-Alle-Folgen-in-der-Uebersicht,podcastcoronavirus134.html ',
    'faq_headline': 'FAQ Coronavirus',
    'found_code': 'A QR code was found',
    'imprint_content': '',
    'imprint_headline': '',
    'input_date_error': 'Invalid date. Please try again.',
    'input_date_error_future': 'The date may not be in the future.',
    'input_date_help': 'Please enter a valid date in form DD.MM.YYYYY which is not in the future. Example: 09.03.2020',
    'input_date_label': 'please enter the date.',
    'input_date_placeholder': 'DD.MM.YYYY',
    'legal_first_paragraph': '',
    'legal_headline': 'Legal matters',
    'q01_option0': 'Younger than 40',
    'q01_option1': '40-50',
    'q01_option2': '51-60',
    'q01_option3': '61-70',
    'q01_option4': '71-80',
    'q01_option5': 'Older than 80',
    'q01_text': 'How old are you?',
    'q02_option0': 'living alone',
    'q02_option1': 'together with family, flat mates or assisted living',
    'q02_text': 'Wie ist Ihre aktuelle Wohnsituation?',
    'q03_option0': 'Housing situation',
    'q03_option1': 'In a community facility (school, day care center, university, home etc.)',
    'q03_option2': 'No, in none of the limited areas',
    'q03_text': 'Are you working in any of the following areas?',
    'q04_text': 'Do you smoke??',
    'q05_text': 'Have you traveled within last 4 weeks?',
    'q16_option0': 'Sate of New York',
    'q16_option1': 'Washington State',
    'q16_option2': 'State of California',
    'q16_text': 'USA: Have you been to one of the following regions?',
    'q17_text': 'On what day did you return from your trip?',
    'q18_text': 'Did you have close contact with a confirmed case?',
    'q19_comment': 'A suspected case is a person who currently has a fever, cough or respiratory distress and has had contact with a confirmed case or has been in a region of high incidence of coronavirus infection. \Long contact with a suspected case means":\ncontact face-to-face for more than 15 minutes\ndirect, physical contact (touching, handshaking, kissing)\nspending more than 15 minutes directly next to an infected person (less than 2 metres)\ncontact with or exchange of body fluids\nparts of an apartment',
    'q19_text': 'Did you have close contact with a suspicious case?',
    'q20_text': 'On what day was the last contact?',
    'q21_text': 'Have you had a fever (over 38 °C) in the last 24 hours?',
    'q22_text': 'Have you had a fever (over 38 °C) in the last 4 days?',
    'q23_option0': 'Less than 38 °C',
    'q23_option1': '38 °C',
    'q23_option2': '39 °C',
    'q23_option3': '40 °C',
    'q23_option4': '41 °C',
    'q23_option5': '42 °C',
    'q23_option6': 'Above 42 °C',
    'q23_option7': "I don't know",
    'q23_text': 'What was the highest temperature approximately?',
    'q24_text': 'Do you have chills?',
    'q25_text': 'Do you feel limp or tired?',
    'q26_text': 'Do you have aching limbs?',
    'q27_text': 'Do you have a persistent cough?',
    'q28_text': 'Do you have a cold?',
    'q29_text': 'Do you have diarrhoea?',
    'q30_text': 'Do you have a sore throat?',
    'q31_text': 'Do you have headaches?',
    'q32_text': 'Are you out of breath faster than usual?',
    'q33_text': 'Since when have you had the symptoms?',
    'q34_text': 'Have you been diagnosed with chronic lung disease?',
    'q35_text': 'Do you have diabetes?',
    'q36_text': 'Have you been diagnosed with heart disease?',
    'q37_text': 'Have you been diagnosed with obesity?',
    'q38_text': 'Are you pregnant?',
    'q39_text': 'Are you currently taking cortisone (in tablet form)?',
    'q40_comment': 'Are you taking or receiving immunosuppressants after an organ transplantation, during the therapy of an autoimmune disease or within the scope of a chemotherapy?',
    'q40_text': 'Are you currently taking immunosuppressants?',
    'q41_text': 'Have you had a flu shot between October 2019 and today?',
    'q42_text': 'On what day did you return from your journey?',
    'qr_code_button_reset': 'Delete answers',
    'qr_code_headline': 'Summary of your answers',
    'qr_code_hide_answers': 'Hide answers',
    'qr_code_paragraph': 'Below you will find an overview of your answers as a table and QR Code.\n\nIf you have received the advice to introduce yourself in an investigating body, please save the following QR Code and the summary of the questions. If possible, print out the summary and show it to others.\n\nWhen you leave the house, keep sufficient distance (more than 2 meters) from other people. If possible, do not touch anything and observe the rules for proper coughing and sneezing.',
    'qr_code_print': 'Print',
    'qr_code_show_answers': 'Display answer',
    'questionnaire_button_generate_qr': 'Close questionnaire',
    'questionnaire_button_next': 'Next',
    'recommendation_risk_high_additonal_info': "Charité location Virchow in Wedding\nMittelallee 1 \nOpen daily 8 a.m. to 4 p.m.\nVivantes-Klinikum Prenzlauer Berg \nDiesterwegstraße \nMo-Fr: 10 to 19 h, Sat/Sun: 10 to 17 h\nVivantes Wenckebach-Klinikum in Tempelhof \nAlbrechtstraße \nMo-Fr: 10 to 19 h, Sat/Sun 10 a.m. to 5 p.m. at the Protestant Hospital Queen Elisabeth Herzberge in Lichtenberg \nHerzbergstraße 79, 10365 Berlin \nMo-Fr: 10 a.m. to 7 p.m., Sat/Sun 10 to 17 o'clock\n\nDRK Kliniken Berlin Westend (Ambulantes Diagnostikzentrum)\nSpandauer Damm 130, 14050 Berlin\nMo-Fr: 9 to 15 o'clock\n\nCoronavirus outpatient clinic in the Gemeinschaftskrankenhaus Havelhöhe\nHaus 16, Kladower Damm 221, Spandau \nMo-Fr: 9 to 17 o'clock The telephone hotline is manned from Mon-Fri from 8 a.m. to 6 p.m. and Sat/Sun 9 a.m. to 3:30 p.m.",
    'recommendation_risk_high_emoji_label': 'Red Circle',
    'recommendation_risk_high_headline': 'Get in touch',
    'recommendation_risk_high_hide_info': 'Hide investigative bodies',
    'recommendation_risk_high_show_info': 'Show investigating bodies',
    'recommendation_risk_high_text': 'You seem to belong to the risk group. \n\nIf you wish, call the hotline of the Senate Health Administration (Tel. 030/9028 28 28) or introduce yourself at one of the examination centres.\nWhen you leave the house, keep a sufficient distance (more than 2 metres) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.\nPlease avoid unnecessary contact with other people and stay at home if possible.',
    'recommendation_risk_low_emoji_label': 'Yellow circle',
    'recommendation_risk_low_headline': 'Pay attention to your hand hygiene',
    'recommendation_risk_low_text': 'You have been in an RKI risk area or have had contact with a person with confirmed or suspected coronavirus infection. Please stay at home and avoid unnecessary contact with other people. \n\nIf your symptoms become more severe in the next few days or you feel unsure, please report to the hotline of the Senate Health Administration (Tel. 030/9028 28 28) or to one of the examination centres. If you are a Berliner, you can also make an appointment at the Charité-Corona video consultation hour at https://bit.ly/2U07tCqvereinbaren.\n\nAvoid unnecessary contact with other people and stay at home if possible. When you leave the house, keep sufficient distance (at least 2 meters) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.',
    'recommendation_risk_medium_emoji_label': 'Orange circle',
    'recommendation_risk_medium_headline': 'Cure yourself and stay calm',
    'recommendation_risk_medium_text': 'As you have not been in any RKI risk area and have not had any contact with a diagnosed case (or suspected case), a smear test for the corona virus is currently not recommended. Stay at home, cure yourself and avoid unnecessary contact with other people.\nIf your symptoms should become stronger in the next few days or you feel unsure, then first call your family doctor or the medical on-call service (+49 116 117) or make an appointment in the online consultation hours of KRY at: https://bit. ly/2QuCZGo\nWhen you leave the house, keep a sufficient distance (more than 2 meters) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.',
    'recommendation_risk_slight_emoji_label': 'Green circle',
    'recommendation_risk_slight_headline': 'Stay at home',
    'recommendation_risk_slight_text': 'There is currently no need for action for you, because you:\nhave not been in contact with a confirmed case\nhave not been in any risk area according to the RKI in the last 14 days\nhave no symptomsPlace increased emphasis on good hand hygieneWhen you leave the house, keep a sufficient distance (more than 2 meters) from other people, do not touch anything, and observe the rules for proper coughing and sneezing.',
    'start_headline': 'Recommended actions and information about the corona virus',
    'start_legal_paragraph': 'The digital application is not an application that provides diagnostic services The application serves to simplify the procedures in the care system.',
    'start_paragraph_1_option_1': 'Contact persons and contacts for Berlin',
    'start_paragraph_1_option_2': "Decision-making aid concerning doctor's visit or coronavirus test",
    'start_paragraph_1_option_3': 'behaviours to reduce the risk of infection',
    'start_paragraph_1_option_4': 'Optimization of patient flows',
    'start_paragraph_2': "The CovApp is a software developed by the Charité in cooperation with Data4Life, with which you can answer a catalogue of questions within a few minutes and receive specific recommendations for action. You will be asked questions about current symptoms, your last trips and possible contacts. This app does not provide diagnostic services. However, after answering the catalogue of questions you will receive specific recommendations for action, contact persons and contacts as well as a summary of your data. The aim is to optimise patient flows to hospitals and examination centres, so the CovApp can help you to better assess the need for a visit to the doctor or coronavirus tests. The medically relevant information for a possible doctor's visit will be summarized for you at the end of the document How do I use the CovApp?\n1. Start the survey by clicking on \"Start questionnaire\"\nThe questionnaire takes about 5 minutes of your time and asks you questions about current symptoms, previous illnesses, travel to risk areas and contact with suspected cases. Try to answer the questions as precisely as possible.\n2. Catalogue of questions and recommendations\nAt the end of the survey you will receive an overview of your answers and specific recommendations for action, such as \nCall one of the hotlines of the public health service\nPresentation to your family doctor\nHome isolation\n3. Preparation for a consultation with a doctor\nIf a consultation with a doctor is necessary, some examination centres offer the possibility of scanning your answers via a QR code (e.g. at the Charité). The use of a QR code to transmit relevant medical information supports further care and helps to process the large number of people seeking help or advice more quickly. \nFor a visit to your general practitioner or to another examination center outside of the Charité, print out the summary at the end or show it during your visit to the doctor.",
    'start_paragraph_3': 'The questionnaire is anonymous and will only be edited and saved on your device (e.g. mobile phone). Your answers will not be transmitted to us or via the Internet to third parties.',
    'start_paragraph_4': 'The use of this app does not replace medical treatment. If you are currently feeling seriously ill, please seek medical help immediately.',
    'start_sub_headline_1': 'Prepare for your medical consultation',
    'start_sub_headline_2': 'What is the CovApp?',
    'start_sub_headline_3': 'What data is transferred via the Internet?',
    'start_sub_headline_4': 'When in doubt, consult a doctor!'
}
