german_text_map = {
    'q16_option0': 'Sate of New York',
    'q16_option1': 'Washington State',
    'q16_option2': 'State of California',
    'q16_text': 'USA: Have you been to one of the following regions?',
    'q17_text': 'On what day did you return from your trip?',
    'q18_text': 'Did you have close contact with a confirmed case?',
    'q19_comment': 'A suspected case is a person who currently has a fever, cough or respiratory distress and has had contact with a confirmed case or has been in a region of high incidence of coronavirus infection. \Long contact with a suspected case means":\ncontact face-to-face for more than 15 minutes\ndirect, physical contact (touching, handshaking, kissing)\nspending more than 15 minutes directly next to an infected person (less than 2 metres)\ncontact with or exchange of body fluids\nparts of an apartment',
    'q19_text': 'Did you have close contact with a suspicious case?',
    'q20_text': 'On what day was the last contact?',
    'q21_text': 'Have you had a fever (over 38 °C) in the last 24 hours?',
    'q22_text': 'Have you had a fever (over 38 °C) in the last 4 days?',
    'q23_option0': 'Less than 38 °C',
    'q23_option1': '38 °C',
    'q23_option2': '39 °C',
    'q23_option3': '40 °C',
    'q23_option4': '41 °C',
    'q23_option5': '42 °C',
    'q23_option6': 'Above 42 °C',
    'q23_option7': "I don't know",
    'q23_text': 'What was the highest temperature approximately?',
    'q24_text': 'Do you have chills?',
    'q25_text': 'Do you feel limp or tired?',
    'q26_text': 'Do you have aching limbs?',
    'q27_text': 'Do you have a persistent cough?',
    'q28_text': 'Do you have a cold?',
    'q29_text': 'Do you have diarrhoea?',
    'q30_text': 'Do you have a sore throat?',
    'q31_text': 'Do you have headaches?',
    'q32_text': 'Are you out of breath faster than usual?',
    'q33_text': 'Since when have you had the symptoms?',
    'q34_text': 'Have you been diagnosed with chronic lung disease?',
    'q35_text': 'Do you have diabetes?',
    'q36_text': 'Have you been diagnosed with heart disease?',
    'q37_text': 'Have you been diagnosed with obesity?',
    'q38_text': 'Are you pregnant?',
    'q39_text': 'Are you currently taking cortisone (in tablet form)?',
    'q40_comment': 'Are you taking or receiving immunosuppressants after an organ transplantation, during the therapy of an autoimmune disease or within the scope of a chemotherapy?',
    'q40_text': 'Are you currently taking immunosuppressants?',
    'q41_text': 'Have you had a flu shot between October 2019 and today?',
    'q42_text': 'On what day did you return from your journey?',
    'qr_code_button_reset': 'Delete answers',
    'qr_code_headline': 'Summary of your answers',
    'qr_code_hide_answers': 'Hide answers',
    'qr_code_paragraph': 'Below you will find an overview of your answers as a table and QR Code.\n\nIf you have received the advice to introduce yourself in an investigating body, please save the following QR Code and the summary of the questions. If possible, print out the summary and show it to others.\n\nWhen you leave the house, keep sufficient distance (more than 2 meters) from other people. If possible, do not touch anything and observe the rules for proper coughing and sneezing.',
    'qr_code_print': 'Print',
    'qr_code_show_answers': 'Display answer',
    'questionnaire_button_generate_qr': 'Close questionnaire',
    'questionnaire_button_next': 'Next',
    'recommendation_risk_high_additonal_info': "Charité location Virchow in Wedding\nMittelallee 1 \nOpen daily 8 a.m. to 4 p.m.\nVivantes-Klinikum Prenzlauer Berg \nDiesterwegstraße \nMo-Fr: 10 to 19 h, Sat/Sun: 10 to 17 h\nVivantes Wenckebach-Klinikum in Tempelhof \nAlbrechtstraße \nMo-Fr: 10 to 19 h, Sat/Sun 10 a.m. to 5 p.m. at the Protestant Hospital Queen Elisabeth Herzberge in Lichtenberg \nHerzbergstraße 79, 10365 Berlin \nMo-Fr: 10 a.m. to 7 p.m., Sat/Sun 10 to 17 o'clock\n\nDRK Kliniken Berlin Westend (Ambulantes Diagnostikzentrum)\nSpandauer Damm 130, 14050 Berlin\nMo-Fr: 9 to 15 o'clock\n\nCoronavirus outpatient clinic in the Gemeinschaftskrankenhaus Havelhöhe\nHaus 16, Kladower Damm 221, Spandau \nMo-Fr: 9 to 17 o'clock The telephone hotline is manned from Mon-Fri from 8 a.m. to 6 p.m. and Sat/Sun 9 a.m. to 3:30 p.m.",
    'recommendation_risk_high_emoji_label': 'Red Circle',
    'recommendation_risk_high_headline': 'Get in touch',
    'recommendation_risk_high_hide_info': 'Hide investigative bodies',
    'recommendation_risk_high_show_info': 'Show investigating bodies',
    'recommendation_risk_high_text': 'You seem to belong to the risk group. \n\nIf you wish, call the hotline of the Senate Health Administration (Tel. 030/9028 28 28) or introduce yourself at one of the examination centres.\nWhen you leave the house, keep a sufficient distance (more than 2 metres) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.\nPlease avoid unnecessary contact with other people and stay at home if possible.',
    'recommendation_risk_low_emoji_label': 'Yellow circle',
    'recommendation_risk_low_headline': 'Pay attention to your hand hygiene',
    'recommendation_risk_low_text': 'You have been in an RKI risk area or have had contact with a person with confirmed or suspected coronavirus infection. Please stay at home and avoid unnecessary contact with other people. \n\nIf your symptoms become more severe in the next few days or you feel unsure, please report to the hotline of the Senate Health Administration (Tel. 030/9028 28 28) or to one of the examination centres. If you are a Berliner, you can also make an appointment at the Charité-Corona video consultation hour at https://bit.ly/2U07tCqvereinbaren.\n\nAvoid unnecessary contact with other people and stay at home if possible. When you leave the house, keep sufficient distance (at least 2 meters) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.',
    'recommendation_risk_medium_emoji_label': 'Orange circle',
    'recommendation_risk_medium_headline': 'Cure yourself and stay calm',
    'recommendation_risk_medium_text': 'As you have not been in any RKI risk area and have not had any contact with a diagnosed case (or suspected case), a smear test for the corona virus is currently not recommended. Stay at home, cure yourself and avoid unnecessary contact with other people.\nIf your symptoms should become stronger in the next few days or you feel unsure, then first call your family doctor or the medical on-call service (+49 116 117) or make an appointment in the online consultation hours of KRY at: https://bit. ly/2QuCZGo\nWhen you leave the house, keep a sufficient distance (more than 2 meters) from other people, do not touch anything if possible and observe the rules for proper coughing and sneezing.',
    'recommendation_risk_slight_emoji_label': 'Green circle',
    'recommendation_risk_slight_headline': 'Stay at home',
    'recommendation_risk_slight_text': 'There is currently no need for action for you, because you:\nhave not been in contact with a confirmed case\nhave not been in any risk area according to the RKI in the last 14 days\nhave no symptomsPlace increased emphasis on good hand hygieneWhen you leave the house, keep a sufficient distance (more than 2 meters) from other people, do not touch anything, and observe the rules for proper coughing and sneezing.',
    'start_headline': 'Recommended actions and information about the corona virus',
    'start_legal_paragraph': 'The digital application is not an application that provides diagnostic services The application serves to simplify the procedures in the care system.',
    'start_paragraph_1_option_1': 'Contact persons and contacts for Berlin',
    'start_paragraph_1_option_2': "Decision-making aid concerning doctor's visit or coronavirus test",
    'start_paragraph_1_option_3': 'behaviours to reduce the risk of infection',
    'start_paragraph_1_option_4': 'Optimization of patient flows',
    'start_paragraph_2': "The CovApp is a software developed by the Charité in cooperation with Data4Life, with which you can answer a catalogue of questions within a few minutes and receive specific recommendations for action. You will be asked questions about current symptoms, your last trips and possible contacts. This app does not provide diagnostic services. However, after answering the catalogue of questions you will receive specific recommendations for action, contact persons and contacts as well as a summary of your data. The aim is to optimise patient flows to hospitals and examination centres, so the CovApp can help you to better assess the need for a visit to the doctor or coronavirus tests. The medically relevant information for a possible doctor's visit will be summarized for you at the end of the document How do I use the CovApp?\n1. Start the survey by clicking on \"Start questionnaire\"\nThe questionnaire takes about 5 minutes of your time and asks you questions about current symptoms, previous illnesses, travel to risk areas and contact with suspected cases. Try to answer the questions as precisely as possible.\n2. Catalogue of questions and recommendations\nAt the end of the survey you will receive an overview of your answers and specific recommendations for action, such as \nCall one of the hotlines of the public health service\nPresentation to your family doctor\nHome isolation\n3. Preparation for a consultation with a doctor\nIf a consultation with a doctor is necessary, some examination centres offer the possibility of scanning your answers via a QR code (e.g. at the Charité). The use of a QR code to transmit relevant medical information supports further care and helps to process the large number of people seeking help or advice more quickly. \nFor a visit to your general practitioner or to another examination center outside of the Charité, print out the summary at the end or show it during your visit to the doctor.",
    'start_paragraph_3': 'The questionnaire is anonymous and will only be edited and saved on your device (e.g. mobile phone). Your answers will not be transmitted to us or via the Internet to third parties.',
    'start_paragraph_4': 'The use of this app does not replace medical treatment. If you are currently feeling seriously ill, please seek medical help immediately.',
    'start_sub_headline_1': 'Prepare for your medical consultation',
    'start_sub_headline_2': 'What is the CovApp?',
    'start_sub_headline_3': 'What data is transferred via the Internet?',
    'start_sub_headline_4': 'When in doubt, consult a doctor!'
}
